// AUTO-GENERATED by scripts/fetch-album-art.mjs — do not edit by hand.
// Re-run `node scripts/fetch-album-art.mjs` to refresh.

import type { Track } from "./detail-types";

export const playlist: Track[] = [
  {
    "id": "track-01-end-of-beginning",
    "title": "End of Beginning",
    "artist": "Djo",
    "album": "DECIDE",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/e5/94/31/e59431de-7591-58e6-c4d4-105b6373ad6a/5056494917336_1.jpg/600x600bb.jpg"
  },
  {
    "id": "track-02-blue",
    "title": "blue",
    "artist": "yung kai",
    "album": "blue",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/33/62/62/33626226-0cf3-ff64-3296-b2355de71fac/0748777703419.jpg/600x600bb.jpg"
  },
  {
    "id": "track-03-cruel-summer",
    "title": "Cruel Summer",
    "artist": "Taylor Swift",
    "album": "Lover",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/49/3d/ab/493dab54-f920-9043-6181-80993b8116c9/19UMGIM53909.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-04-photograph",
    "title": "Photograph",
    "artist": "Ed Sheeran",
    "album": "x",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/2d/36/f9/2d36f9a7-2c3e-ce0f-7fb6-036feecb221f/825646974450.jpg/600x600bb.jpg"
  },
  {
    "id": "track-05-viva-la-vida",
    "title": "Viva La Vida",
    "artist": "Coldplay",
    "album": "Viva La Vida or Death and All His Friends",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/52/aa/85/52aa851f-15b7-6322-f91f-df84b15b7b19/190295978044.jpg/600x600bb.jpg"
  },
  {
    "id": "track-06-stitches",
    "title": "Stitches",
    "artist": "Shawn Mendes",
    "album": "Handwritten",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/e3/d4/de/e3d4def5-886e-da47-e1cf-568566510b53/15UMGIM62454.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-07-treat-you-better",
    "title": "Treat You Better",
    "artist": "Shawn Mendes",
    "album": "Illuminate",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/dd/bb/b7/ddbbb775-836a-f7da-f89a-f33029f6ef4a/16UMGIM51585.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-08-attention",
    "title": "Attention",
    "artist": "Charlie Puth",
    "album": "Voicenotes",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/a8/e2/1b/a8e21b3b-9c8d-2974-2318-6bcd4c9d2370/075679884336.jpg/600x600bb.jpg"
  },
  {
    "id": "track-09-careless-whisper",
    "title": "Careless Whisper",
    "artist": "George Michael",
    "album": "Ladies & Gentlemen",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/89/46/95/8946959a-e959-f22d-ced2-745feb799454/mzm.upagbaeg.jpg/600x600bb.jpg"
  },
  {
    "id": "track-10-stereo-hearts",
    "title": "Stereo Hearts",
    "artist": "Gym Class Heroes",
    "album": "The Papercut Chronicles II",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music/dc/f0/93/mzi.stzaqjgi.jpg/600x600bb.jpg"
  },
  {
    "id": "track-11-i-want-it-that-way",
    "title": "I Want It That Way",
    "artist": "Backstreet Boys",
    "album": "Millennium",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/5f/6b/e9/5f6be919-1b9e-30ef-45b7-cc27fc428fd5/012414167224.jpg/600x600bb.jpg"
  },
  {
    "id": "track-12-night-changes",
    "title": "Night Changes",
    "artist": "One Direction",
    "album": "FOUR",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/62/2d/19/622d19da-eb88-022c-2bc5-d843657defe8/886444549851.jpg/600x600bb.jpg"
  },
  {
    "id": "track-13-yellow",
    "title": "Yellow",
    "artist": "Coldplay",
    "album": "Parachutes",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/f5/93/8c/f5938c49-964c-31d1-4b33-78b634f71fb7/190295978075.jpg/600x600bb.jpg"
  },
  {
    "id": "track-14-mary-on-a-cross",
    "title": "Mary On A Cross",
    "artist": "Ghost",
    "album": "Seven Inches of Satanic Panic",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/20/72/d3/2072d3b2-238c-1ac2-1f6f-21f683fdc41b/24CRGIM45902.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-15-demons",
    "title": "Demons",
    "artist": "Imagine Dragons",
    "album": "Night Visions",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/1f/fa/09/1ffa092f-f52f-4a66-7d10-4cc5982dc747/12UMGIM46901.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-16-love-the-way-you-lie",
    "title": "Love The Way You Lie",
    "artist": "Eminem",
    "album": "Recovery",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/95/a4/2c/95a42c0d-f3c8-c70d-3e3a-93cfa4a516d4/00602527394558.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-17-soft-spot",
    "title": "Soft Spot",
    "artist": "keshi",
    "album": "Requiem",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/fc/1d/9e/fc1d9e9d-5d56-b34d-56ef-53cb83979fd2/24UM1IM24742.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-18-one-last-time",
    "title": "One Last Time",
    "artist": "Ariana Grande",
    "album": "My Everything",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/a5/39/86/a5398609-ad90-50d3-57ad-0f87a4df5ac4/14UMGIM28138.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-19-golden-hour",
    "title": "golden hour",
    "artist": "JVKE",
    "album": "this is what feels like",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/8d/1a/7b/8d1a7b44-316f-7c7f-4380-935673fb697a/5056167175650.jpg/600x600bb.jpg"
  },
  {
    "id": "track-20-until-i-found-you",
    "title": "Until I Found You",
    "artist": "Stephen Sanchez",
    "album": "Angel Face",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/64/d2/c5/64d2c511-67f4-ae09-5153-d39c3da413a3/21UMGIM75467.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-21-back-to-friends",
    "title": "back to friends",
    "artist": "sombr",
    "album": "I Barely Know Her",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/5d/d5/ad/5dd5ad1b-fabf-9218-77f0-3adbfd5328ac/054391237118.jpg/600x600bb.jpg"
  },
  {
    "id": "track-22-we-don-t-talk-anymore",
    "title": "We Don't Talk Anymore",
    "artist": "Charlie Puth",
    "album": "Nine Track Mind",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/7e/05/fd/7e05fd3e-597b-db52-5d87-3ed146d2e2bb/mzm.omtrmqdi.jpg/600x600bb.jpg"
  },
  {
    "id": "track-23-heather",
    "title": "Heather",
    "artist": "Conan Gray",
    "album": "Kid Krow",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/18/08/a1/1808a1be-b5a9-5e69-583d-b8a357efd760/19UM1IM12338.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-24-glimpse-of-us",
    "title": "Glimpse of Us",
    "artist": "Joji",
    "album": "SMITHEREENS",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/d0/2a/43/d02a433a-3ab8-9a94-b07d-1dc599b64966/93624864387.jpg/600x600bb.jpg"
  },
  {
    "id": "track-25-somewhere-only-we-know",
    "title": "Somewhere Only We Know",
    "artist": "Keane",
    "album": "Hopes And Fears",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/89/a6/f7/89a6f7be-a0e0-2524-a13b-6b5df7b7534a/06UMGIM24399.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-26-atlantis",
    "title": "Atlantis",
    "artist": "Seafret",
    "album": "Tell Me It's Real",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/34/65/51/34655139-b2e9-d623-8c4c-e19975efb02b/dj.figvivao.jpg/600x600bb.jpg"
  },
  {
    "id": "track-27-2-soon",
    "title": "2 soon",
    "artist": "keshi",
    "album": "2 soon",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/8c/64/1b/8c641bf4-e3cc-8895-e41a-7b34c03c31b6/21UMGIM32368.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-28-wantchu",
    "title": "WANTCHU",
    "artist": "keshi",
    "album": "WANTCHU",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/0f/c9/1f/0fc91f9d-dcbf-687c-3841-13902a95cbf6/25UM1IM00469.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-29-drunk-text",
    "title": "drunk text",
    "artist": "Henry Moodie",
    "album": "in all of my lonely nights",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/61/3d/a6/613da60e-5b3d-7305-19db-ed79f5aa0b05/196589768643.jpg/600x600bb.jpg"
  },
  {
    "id": "track-30-war",
    "title": "War",
    "artist": "keshi",
    "album": "Requiem",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/a6/a3/20/a6a32054-f43f-12b3-4019-1f201b6c56b2/24UMGIM70300.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-31-i-think-they-call-this-love",
    "title": "I Think They Call This Love",
    "artist": "Elliot James Reay",
    "album": "I Think They Call This Love",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/30/a8/f1/30a8f1b6-e75d-55b4-ee88-667a062e0103/24UM1IM12416.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-32-spring-snow",
    "title": "Spring Snow",
    "artist": "10CM",
    "album": "Lovely Runner Pt. 8",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/13/e6/e8/13e6e889-c2a5-95f0-2936-5c3994fb306e/888272134100_Cover.jpg/600x600bb.jpg"
  },
  {
    "id": "track-33-everytime",
    "title": "Everytime",
    "artist": "Chen",
    "album": "Descendants Of The Sun Pt.2",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/6d/80/7f/6d807fdc-677a-89dc-d45a-aa264e62b994/8809492016207.jpg/600x600bb.jpg"
  },
  {
    "id": "track-34-bodies",
    "title": "Bodies",
    "artist": "keshi",
    "album": "Requiem",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/a6/a3/20/a6a32054-f43f-12b3-4019-1f201b6c56b2/24UMGIM70300.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-35-intentions",
    "title": "intentions",
    "artist": "starfall",
    "album": "alone tonight",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/e1/90/94/e1909459-2e3c-8a3c-ff4e-b55293e20857/1963621350598_cover.jpg/600x600bb.jpg"
  },
  {
    "id": "track-36-cry",
    "title": "Cry",
    "artist": "Cigarettes After Sex",
    "album": "Cry",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music113/v4/a2/1e/b4/a21eb48e-05ac-ace3-00f5-c1cb53e74e58/720841217305_Cover.jpg/600x600bb.jpg"
  },
  {
    "id": "track-37-vodka-cranberry",
    "title": "Vodka Cranberry",
    "artist": "Conan Gray",
    "album": "Wishbone",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/1b/95/f6/1b95f6d8-dcbd-2ce0-2c35-f2336de9bbc2/25UMGIM71376.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-38-i-love-you-so",
    "title": "I Love You So",
    "artist": "The Walters",
    "album": "I Love You So",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/95/a5/14/95a514ab-1f06-81dd-8a60-f7ca13a172ce/054391911063.jpg/600x600bb.jpg"
  },
  {
    "id": "track-39-memories",
    "title": "Memories",
    "artist": "Conan Gray",
    "album": "Superache",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/13/eb/23/13eb23c3-ac62-f3c1-46f9-2d6f56a01b66/22UMGIM34487.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-40-the-exit",
    "title": "The Exit",
    "artist": "Conan Gray",
    "album": "Superache",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/cd/ea/7f/cdea7f8e-9d63-3d7f-e54b-4df8bc3520c0/22UMGIM49870.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-41-maniac",
    "title": "Maniac",
    "artist": "Conan Gray",
    "album": "Kid Krow",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/18/08/a1/1808a1be-b5a9-5e69-583d-b8a357efd760/19UM1IM12338.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-42-those-eyes",
    "title": "Those Eyes",
    "artist": "New West",
    "album": "Based On A True Story",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music123/v4/eb/56/0b/eb560b22-e411-02e8-4608-6961e2c0d90f/23UMGIM00586.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-43-that-should-be-me",
    "title": "That Should Be Me",
    "artist": "Justin Bieber",
    "album": "My World 2.0",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/b9/0a/b4/b90ab45a-07b1-0bcc-331c-c496a21d07e4/10UMGIM01134.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-44-beauty-and-a-beat",
    "title": "Beauty And A Beat",
    "artist": "Justin Bieber",
    "album": "Believe",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/73/08/1a/73081a96-0f7c-b5f8-2757-5c17fb714323/12UMGIM31899.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-45-love-yourself",
    "title": "Love Yourself",
    "artist": "Justin Bieber",
    "album": "Purpose",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/75/11/84/751184b0-77df-1eff-bb20-dac03247425d/15UMGIM59808.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-46-eenie-meenie",
    "title": "Eenie Meenie",
    "artist": "Sean Kingston",
    "album": "Eenie Meenie EP",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/f7/95/b3/f795b313-0788-da18-36c4-7c30220691a8/mzi.edakdecd.jpg/600x600bb.jpg"
  },
  {
    "id": "track-47-good-luck-babe",
    "title": "Good Luck, Babe!",
    "artist": "Chappell Roan",
    "album": "Good Luck, Babe!",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/29/a7/c4/29a7c478-351d-25eb-a116-3e68118cdab8/24UMGIM31246.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-48-lonely",
    "title": "Lonely",
    "artist": "Justin Bieber",
    "album": "Justice",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/b9/d9/e1/b9d9e1cf-c187-5d03-a2ca-2565bd4f1e5d/20UMGIM83529.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-49-actor",
    "title": "Actor",
    "artist": "Conan Gray",
    "album": "Wishbone",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/50/0b/9a/500b9aba-d89a-8a93-dfaf-9d4177199c42/25UMGIM71376.rgb.jpg/600x600bb.jpg"
  },
  {
    "id": "track-50-yukon",
    "title": "YUKON",
    "artist": "Justin Bieber",
    "album": "SWAG II",
    "albumArt": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/f9/09/36/f9093663-c05f-7f95-0a60-4e95d52fbb22/25UMGIM93915.rgb.jpg/600x600bb.jpg"
  }
];
